name: CI

on:
  push:
    branches:
    - main
    - release/*
    
on:
  pull_request:
    branches:
    - main
    
on:
  schedule:
  - cron: "0 2 * * 1-5"
  
on:
    
  workflow_dispatch:
  
jobs:

  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo KarubuApp!!!
        
      - name: Run a multi-line script
        run:
          echo Add other actions to build.
          echo test, and deploy your project.
        
    
